# Generated by Django 3.2.9 on 2022-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charName', models.CharField(max_length=100)),
                ('charClass', models.CharField(default='Sin Rol', max_length=100)),
                ('charSex', models.CharField(max_length=100)),
                ('charHp', models.IntegerField(default=1)),
                ('charStr', models.IntegerField(default=0)),
                ('charSkl', models.IntegerField(default=0)),
                ('charSpd', models.IntegerField(default=0)),
                ('charLk', models.IntegerField(default=0)),
                ('charDef', models.IntegerField(default=0)),
                ('charRes', models.IntegerField(default=0)),
                ('charHpGrowth', models.IntegerField(default=0)),
                ('charStrGrowth', models.IntegerField(default=0)),
                ('charSklGrowth', models.IntegerField(default=0)),
                ('charSpdGrowth', models.IntegerField(default=0)),
                ('charLkGrowth', models.IntegerField(default=0)),
                ('charDefGrowth', models.IntegerField(default=0)),
                ('charResGrowth', models.IntegerField(default=0)),
            ],
        ),
    ]
