# Generated by Django 3.2.9 on 2022-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadChar', '0002_character_charcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
